services:
  - type: web
    name: research
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port=$PORT --server.address=0.0.0.0
    plan: free

    buildFilter:
      paths:
        - "**/*"

    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: MODEL_NAME
        value: gpt-4o-mini

    aptPackages:
      - tesseract-ocr
      - poppler-utils
